### PR TITLE
convert to string before comparing on element_name_should_be keyword

### PR DESCRIPTION
**Pull request by minhnguyenphuonghoang**
Sometimes, when I use this keyword, I got the following error message:
Element '//UIAApplication[1]/UIAWindow[2]/UIATableView[1]/UIATableCell[2]/UIAStaticText[2]' name should be '12' but it is '12'.

My current solution is to avoid comparing different type of variable, I just converted them to String variable then make comparison.

### CODE REVIEW

**Comment by jollychang** [comment]
both '//UIAApplication[1]/UIAWindow[2]/UIATableView[1]/UIATableCell[2]/UIAStaticText[2]' and '12' are string?

**Comment by minhnguyenphuonghoang** [comment]
'//UIAApplication[1]/UIAWindow[2]/UIATableView[1]/UIATableCell[2]/UIAStaticText[2]' this is element locatior, String yes
'12': this is expectation
and another '12' is current value

**Comment by jollychang** [comment]
Could you chang all string compare too? such as `element_value_should_be `?

**Comment by minhnguyenphuonghoang** [comment]
I have committed the fix for element_value_should_be
https://github.com/jollychang/robotframework-appiumlibrary/commit/ba6e5a4b64ca1d6a0a84a38465afa71e0205606c

**Comment by jollychang** [comment]
Thanks

**Pull request merged**
