### PR TITLE
add new keyword capture page screenshot with unique name

### PR DESCRIPTION
**Pull request by minhnguyenphuonghoang**

### CODE REVIEW

**Comment by serhatbolsu** [comment]
I dont really see the point in this, actually capture screenshot result already had an unique name and better they were ordered from 0 to xx which is much easier to track in case you use an listener or such after execution tool

**Comment by minhnguyenphuonghoang** [comment]
Hi @serhatbolsu 
You're absolutely right if we run tests only 1 time.

Assuming we need to run our tests 2 or more times (right after the 1st test failed, we only run all failed tests then merge the result) so, we have a lot of log directories which contains a lot of screenshots. In each directory, the screenshot index will start from 1 and we have no way to view the screenshot in the final log/output file.

This keyword will support us to do this.
rebot (Robot Framework Report) can't do anything with these screenshots.

**Comment by serhatbolsu** [comment]
In that case, it makes sense to have this keyword, even though complicates the library. Regarding implementation, do you think you really need `random`since it is milli seconds.

**Comment by minhnguyenphuonghoang** [comment]
Yup,

I've thought a lot about this thing before I started coding this function.
Actually, we don't really need this implementation (I mean `random`) like you said.
But what I'm trying to avoid here is someone can use our library to run `parallel-tests` on multiple devices (we're supporting running tests on multiple android devices and maybe in the future, we can also run our test on multiple iOS devices too). The report should be separated into different directories. BUT, if someone wants to put it together, we still can support him to do that.

Sure, if you decline my opinion, I can make another pull request without this random too.
How do you think?

**Comment by jollychang** [comment]
You can generate specific report folder by robotframeworks report lib

**Pull request closed without merging**
