### PR TITLE
add new keyword capture page screenshot with unique name

### PR DESCRIPTION
**Pull request by minhnguyenphuonghoang**
For supporting feature merge report in Robot Framework, we need all screenshots should have a unique name.
I've added a public keyword `Capture Page Screenshot With Unique Name`

From the following discussion, I removed the `random` keyword to make it 'less complex'.
https://github.com/jollychang/robotframework-appiumlibrary/pull/78

### CODE REVIEW

**Comment by jollychang** [comment]
1. You can split report and log then merge by shell (such as use specific folder name ) http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#different-output-files
1. You can modify `capture_page_screenshot`

**Comment by minhnguyenphuonghoang** [comment]
OK got it
Thanks

**Comment by minhnguyenphuonghoang** [comment]
Hi @jollychang
I have thought about everything you said.

Assuming we have this case:
5 tests will be run (each test produces 2 screenshots)
First round:
1. pass (2 screenshots - index = 2)
2. failed 
3. pass (2 screenshots - index = 4)
4. pass (2 screenshots - index = 6)
5. failed

Round 2 (only run failed test)
2. pass (2 screenshots - index = 2)
5. failed

After run 2 rounds, I'll merge report/output and copy all screenshots.
The problem is screenshots in round 2 have been reindexed from 1!

So after report has been merged. The 2nd test report/log file will refer to screenshots of test 1st since its index are appium-screenshot-1.png and appium-screenshot-2.png

We have no way to support it.



For the second idea you gave to me: "modify `capture_page_screenshot`"
What does it mean?
I have to fork your project, make changes then install that lib?

I really need your advice.
Thanks in advance.

**Comment by jollychang** [comment]
"modify capture_page_screenshot" mean generate random screenshot file, such as 
`appium-screenshot-{random}.png`

**Comment by minhnguyenphuonghoang** [comment]
Thanks

I can handle it by using a different method

**Pull request closed without merging**
