### PR TITLE
modify to parse "element<0x20>" appropriately

### PR DESCRIPTION
**Pull request by lucyking**
strip() will wipe blanks off at the str end
lead to can't locate the element that has blank postfix in content-desc. 
with the fix now we can locate these exotic element in this way:
```
Mobile_Click_Element    accessibility_id="value  "
```

### CODE REVIEW

**Comment by serhatbolsu** [comment]
@lucyking this does not make much sence to me, why would you send an ill formatted criteria to find?

You could use robotframework string library to fix your criteria, I dont believe this should be a part of appiumlibrary. Also it might be possible `"` is a part of actual criteria that you are looking for in application

**Comment by jollychang** [comment]
same as @serhatbolsu .
it's too magic，close.

**Comment by lucyking** [comment]
@serhatbolsu  in practice some criteria has that bad formatted:
pic0
pic
If criteria has ```"``` itself, we can use  ```accessibility_id=""value  ""``` to deliver it's value.
Because the code just strip one couple of ```"```,not ```.strip.('\"')```will strip severial chars.

**Comment by serhatbolsu** [comment]
If thats the case, removing `.strip()` is an idea. Need to check examples of this, we should make sure this does not break test cases for other people. Actually if this is done, I am sure it will, so best would be to fork the library

**Comment by lucyking** [comment]
at first I also removing ```.strip()```,but it will not remove blanks beside = any more:
 ```accessibility_id<blank>=<blank>value``` -->
*loctae*:```accessibility_id<blank>```
*criteria*:```<blank>value```.
If tester write case not strictly,or RIDE's tabs is tranformed to blanks, removing ```.strip()``` may lead to more bugs.
May forking the lib is better.

**Pull request closed without merging**
