### PR TITLE
Selenium selector fix

### LINKED ISSUE #57: Selectors are broken with Selenium 2.46.1
I have tried id selector with selenium 2.46.1, something is diffrent and id directs to css selector. 
This breaks appium execution as it tries to parse css selector instead of id

### PR DESCRIPTION
**Pull request by serhatbolsu**
Fixes #57

### CODE REVIEW

**Comment by serhatbolsu** [comment]
This is only a temporary fix before identifing actual problem. Python client may have a bug or need update for new selenium version

**Comment by jollychang** [comment]
@serhatbolsu Could you update python client?

**Comment by serhatbolsu** [comment]
@jollychang i have installed all from 0 point. The latest python client make you use selenium 2.46.1 
Then when find_by_id starts to send css as selector. I debugged appiumlibrary, everything was okkay until python client makes the call. Also tested with selenium 2.46, all works okkay then

**Comment by jollychang** [comment]
Thanks @serhatbolsu

**Pull request merged**
